from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from ...authentication import CookieJWTAuthentication
from ...exceptions import InvalidTOTPCode, SetupRequired, TwoFAAlreadyEnabled
from ...serializers import Enable2FASerializer
from ...services import TOTPService
from ...utils import get_or_create_2fa


class Enable2FAView(APIView):
    """
    POST /api/auth/2fa/enable/

    Verifies a TOTP code against the pending secret generated by Setup2FAView
    and, if valid, permanently enables 2FA for the account. Backup codes are
    returned once — store them safely.
    """

    authentication_classes = [CookieJWTAuthentication]
    permission_classes = [IsAuthenticated]
    serializer_class = Enable2FASerializer

    def post(self, request):
        user = request.user

        twofa = get_or_create_2fa(user)

        if getattr(twofa, "is_2fa_enabled", False):
            raise TwoFAAlreadyEnabled()
        if not getattr(twofa, "totp_secret", None):
            raise SetupRequired()

        serializer = Enable2FASerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        if not TOTPService.verify_code(
            twofa.totp_secret, serializer.validated_data["code"]
        ):
            raise InvalidTOTPCode()

        backup_codes = TOTPService.generate_backup_codes()
        twofa.is_2fa_enabled = True
        twofa.backup_codes = backup_codes
        twofa.save(update_fields=["is_2fa_enabled", "backup_codes"])

        return Response(
            {
                "detail": "Two-factor authentication enabled.",
                "backup_codes": backup_codes,
            },
            status=status.HTTP_200_OK,
        )
