# Generated by Django 6.0.4 on 2026-05-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_backup_codes_customuser_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totp_secret',
        ),
    ]
